const fs = require("fs");
const notes = require("../model/notes");

const handleUpload = async (file) => {
  // file.destination is the folder where the file is saved
  // file.filename is the name of the file
  const newFilePath = `${file.destination}${file.filename}.md`;

  await fs.promises.rename(file.path, newFilePath);

  const newNote = {
    name: file.originalname, // The original name of the uploaded file
    id: file.filename, // The unique filename generated by multer
  };

  // Add the note to the notes collection
  notes.add(newNote);
};

module.exports = handleUpload;
